MODEL_SIZE = "small" #tiny

SAMPLE_RATE = 48000
WHISPER_SAMPLE_RATE = 16000

FRAME_MS = 30
SILENCE_MS = 100
MIN_SPEECH_MS = 300
MAX_UTTERANCE_SECONDS = 8

WHISPER_LANGUAGE = "pl"

WHISPER_DEVICE = "cuda" #cpu jeszcze 
WHISPER_COMPUTE_TYPE = "float16"
WHISPER_CPU_THREADS = 6

TRANSLATION_SOURCE = "pl"
TRANSLATION_TARGET = "en"